#!/usr/bin/env ruby
$:.unshift ENV['WEGASOO_PATH'] if ENV['WEGASOO_PATH']
require 'action_space'
require 'ftools'

WEGASOO_CONF = File.expand_path(ENV['WEGASOO_CONF']||"~/.wegasoo")

unless File.directory?(WEGASOO_CONF)
    Wegasoo::Formatting.special("initializing Wegasoo in #{WEGASOO_CONF}")
    Dir.mkdir(WEGASOO_CONF)
    Dir.mkdir(File.join(WEGASOO_CONF,'plugins'))
    File.open(File.join(WEGASOO_CONF,'actions'),'w') do |f|
        f.write "--- {}\n"
    end
end


Dir[File.join(WEGASOO_CONF, 'plugins/*.rb')].each{|p|load p}

$was = Wegasoo::ActionSpace.new
$was.load_file File.join(WEGASOO_CONF, 'actions')

if File.directory?('.wgs')
    Dir['.wgs/plugins/*.rb'].each{|p|load p}
    $was.load_file '.wgs/actions'
end

if File.directory?('/etc/wgs')
    Dir['/etc/wgs/plugins/*.rb'].each{|p|load p}
    $was.load_file '/etc/wgs/actions'
end

case (ad = ARGV.shift)
when 'wgs:plugins:add'
    file = ARGV.shift
    Wegasoo::Formatting.special("adding plugin #{file}")
    File.copy(file,File.join(WEGASOO_CONF,'plugins',File.basename(file)))
when 'wgs:plugins:remove'
    plugin = ARGV.shift
    Wegasoo::Formatting.special("removing plugin #{plugin}")
    File.delete File.join(WEGASOO_CONF,'plugins',File.basename(plugin))
when 'wgs:actions:add'
    file = ARGV.shift
    Wegasoo::Formatting.special("adding action #{file}")
    y = YAML.load_file(File.join(WEGASOO_CONF, 'actions'))
    y.update(YAML.load_file(file))
    File.open(File.join(WEGASOO_CONF, 'actions'), 'w'){|f|f.write YAML.dump(y)}
when 'wgs:actions:remove'
    task = ARGV.shift
    Wegasoo::Formatting.special("removing action #{task}")
    y = YAML.load_file(File.join(WEGASOO_CONF, 'actions'))
    cc = y
    task.split(":")[0..-2].each do |seg|
        cc = cc[seg]
    end
    cc.delete task.split(":")[-1]
    File.open(File.join(WEGASOO_CONF, 'actions'), 'w'){|f|f.write YAML.dump(y)}
when 'wgs:list'
    pd = 0
    puts "\e[32mwgs\e[0m\n\t\e[32mplugins\e[0m\n\t\t\e[32m\e[1madd\e[0m\n\t\t\e[32m\e[1mremove\e[0m\n\t\e[32mactions\e[0m\n\t\t\e[32m\e[1madd\e[0m\n\t\t\e[32m\e[1mremove\e[0m\n\t\e[32m\e[1mlist\e[0m"
    prcu = proc do |n,a|
        case a
        when Hash
            puts "#{"\t"*pd}\e[34m#{n}\e[0m"
            pd += 1
            a.each &prcu
            pd -= 1
        when String
            puts "#{"\t"*pd}\e[34m\e[1m#{n}\e[0m"
        end
    end
    prcs = proc do |n,a|
        case a
        when Hash
            puts "#{"\t"*pd}\e[36m#{n}\e[0m"
            pd += 1
            a.each &prcs
            pd -= 1
        when String
            puts "#{"\t"*pd}\e[36m\e[1m#{n}\e[0m"
        end
    end
    prcd = proc do |n,a|
        case a
        when Hash
            puts "#{"\t"*pd}\e[33m#{n}\e[0m"
            pd += 1
            a.each &prcd
            pd -= 1
        when String
            puts "#{"\t"*pd}\e[33m\e[1m#{n}\e[0m"
        end
    end
    YAML.load_file(File.join(WEGASOO_CONF, 'actions')).each &prcu
    YAML.load_file('.wgs/actions').each &prcd if File.directory?('.wgs')
    YAML.load_file('/etc/wgs/actions').each &prcs if File.directory?('/etc/wgs')
else
    $was.run ad
end
